server.port=8089
spring.application.name=pricing-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/easymonitor
spring.datasource.username=easymonitor
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
