otel.exporter.otlp.endpoint=http://localhost:4317
otel.logs.exporter=otlp
otel.metrics.exporter=none
otel.traces.exporter=otlp

# Enable standard Spring Boot SLF4J log auto-instrumentation 
# provided by the opentelemetry-logback-appender starter.
logging.pattern.level=%5p [spanId=%X{span_id} traceId=%X{trace_id}]
